name: Feature request
description: 提出一个新特性或改进建议
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: 背景与动机
      placeholder: 为什么需要这个功能？解决什么问题？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案与设计
      placeholder: 简述接口、配置键、行为与兼容性
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      placeholder: 是否有其他解决方式？
  - type: textarea
    id: extra
    attributes:
      label: 其他信息